
image: python:3.9

before_script:
  - python --version  # For debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

.test:
  script:
    - pip install tox codecov pre-commit
    - tox

test:
  extends: .test
  variables:
    TOXENV: py39

deploy:
  environment: deploy
  script:
    - cp $PYPIRC $HOME/.pypirc # get your specific pypi config
    - python setup.py bdist_wheel upload -r local-da # replace local-da with your pypi setting
  artifacts:
    paths:
      - dist/*.whl
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
