language: python
python:
- '3.6'
script:
- pytest
services:
- rabitmq
- mongodb
deploy:
  provider: pypi
  user: jeremycward
  password:
    secure: qY9mGzSGXaQ4E8EC1OyTS9bJ8L2BRrNbHuIQnwko66tkXgxxh67t+cve2LkeEHOKZSmq/21LkRf8qsRPaSPAOSo6sNFdkI6KG/oWYDUUUrmEUOZHN4T2qw9w9PynhohG8qFVA90maPKLH3wWnbgJk+i2ff2ygLLJKB0RrOj2S1j5qtlGJHoBI7/gKrQs9ikpmr6JLwKzfjOuR4xmFRGsZepGyeLxyMS4sSvlwXY1G9I9p35XGquHmeG6G/di2w+bamvBxxVjiQzNddxUxmAQqNTu4xny6k2nT9BOqwKi9WpIlw4tAhqwRSdLU6OxRrOhyj50GhOyEFj3tO1YM1xpgRk+IVMMKnGZc9qam8dpKACAsQnTysbyP59F0glTuN5KyzgDDJDQjpR4l4IGoE/0TJl0bCMw6cfvaHaPm7uKJqrsyxRtI+ZzA65VRNuPs2F2ANVCJV5lAn00onA2F1xQTpbLXJnZmvsDzfDeT0qNulz8BhNfskZevCtJ8KcqpEoKiGaGyh2fy35Kh2VIViAyRVn6w+tyOSM9bJ4R86bqeaf0fhjmKUU8nY7jir1c9avwAifiqZNH0DuGu5L8ZJg7U1hJaPfvzaNMLjZjd0J1L6jZ/OJVxWT3ll8j2bunULMj1Q5vwsp8IIohvWzOFWbPgQTtoiNf8y95tX7ocObCGK8=
  skip_cleanup: true
  on:
    tags: true
'':
env:
  global:
        - secure: KCuXQYzD6DbXlNlMV96Svu4UaqPnSD2rKIZQeBer+6mfThqcmFMCU6Qt2DZ/8cMlet9a/bSuPCwx5dUh9/JUCM1ReMLv+rvub3kWIcma/VKYiQmprtQrFNmnYrXD6wgAnfl/ciVJsIx/XhktIfY3FLwsFLlUOAZ28uuo3fryutvT7Q6EHMEw9Pony7fEiLrW2PPSUgAf7blOLZMsogML7tivP74Z1isPKao2bHRJJb2SAMKXiiueswCKVDaaplVkQvwe8C7ZRgv2bhG5mIqKddjxhVZecrI95WFpVF9SVsP+TiCyGau+nCcgppoZzeYi3+zTGcpMDhizZYJylV3JoNjzWmG2w1X5xGcfAEP6tGw/GouWDZq8ZaWFMO7JbkPrw1+Pu3S1DNUWuotnxF5md1RtU3daK0VVit68t00cVLZsk/4cPnhMWut0A28OolQ5MeSa0s/ONwPJfc9SHzuyz0rMfR7oqZ5ctVz66Ecpyyys6cs8B/0es13ulg85Uf94JxpWUjYv9+DxUiHR2OvfA2A6V/avN46Kzjb4gDeqbddrJlG56jNTrU7DDsDV1IaD6mymkaw6I0CUrpulf/IAUUTSRUVeVW+m/lCdhvJwhO4TfEl2VCqCTlrWOaJI+cU4YNy0k0rHJ3/OYwmmCurcLQF0DIf98F/kX/dfkyOKfr0=
        - secure: LC12/5hklx7BUFCeFJYHJOnpH7nsppkHQq7gW5yDZ9ylbfaIhHEoNKG64QnL3xoIqXFG3f46BBBtcq++itXRu6QnQOorE2yZEquoogzU82gRZUyDXsn89DQW9PTmI5jRvwcdWZ3wM57DoMsv70Z1wk0CYe407bciYGLagfzC6o/Gv/6RUENdyPi2nXw1xFqKvQaaErAOjqn0Vq4pWDjFRh6HrGj8b/J/o6GWMvWSG+lH8TjOsz2bx3GrdUSaJLWO71QQ6ooe5ZQHxpFdDGOnMUTPwZ/hUufJOkqHWq3R6hOT3EvVBObPxuDAdcjKgmF9dSk5oa1uH5ZEIoOu77kjBROsurbB3Un7Rr6OdxH46w/XnmSJKDSWRpvxAEd6RFgSRCx0v6rfS31TArtn0qcXSESSMvlnpZTNUhN1YbCnL5yqbFL9HRYKTRbvGJStXYNu3wMO7zcimUnblCdLq/lOFFZj5FI8CDDoDVggIAOyzKDvV/+Qxt3yepGJ2DirBIvpjX0hiG1g8qooIjhdstWfeVke+xtnLtL6eXN8U//upMXVFybQYGaRRNcnVofSGvlDD0y7My9AMAuiWkhW4Btq+pcAkgSg0i//ivciqnMtnwUGtD0sY9SMEx1aBNImrogRMsaRk+MBfx/cA1kiZwLAeBjkE9hUv4i3VHtJFs0GPBE=
        - secure: AIL0+V3RVx2ag+J1g1mD7KR3BEskWHAbzaQUL754Q77EgrutIgkHNaJ08Mwza63qzQ7hWsp6hPSP8bmdxzTReUaGPW8U982K3NRYfpteVKX3nLkypLimUdsf3QuvzzTftZotUiQ6FHBtMrYQMTTgHZmk/6NDOI9+eHmaRHGYljgPQc6fLh7jHhbn7k08K65q8CAF6E2dnPO8g+q8Z0g0FB5I+c/OjXUhEW1MGjkCoxNiFuY6L3ewpPyn3A3b3eCkavXlkwqTXjtd3f83dSen8is78+0WBiaKSWbZgKhGnsf+YkCVMjkAxVwRe5ODdq1/Wa8lD24rwhwD0h0Q0MVfcP+qECMQQDGn5njpWuO3ISph0z2ejf5xVOO6iQmf4M6LIvKx7BrWUtItqQIMQLgnE0tl5IRoav/pmVUKqvGStqn6adSOcdX4kwR8IU3JHmOleEQcN05+yzfjyj2jK08fnYlzOPopflXjq7v4DBORrjRn7KbcTyYmkBr172f7NOj4foCO5cnG9p56T7UiVF/AjXSlEm6X0JC63ZT0E7BWTG1Wso0PTvwvR6g4WSwLnQfZAojnZIQ5x+BNx7ROL8MaCD5cWzbedm8QnO3Apozj2IIq4ys2Q9k5YnVIm9hk5evacdlFRyP3MJzOHNMoBpbF5YY9iEzn7tY9Mz/lmKQ/Obc=
        - COMMIT=${TRAVIS_COMMIT::8}

after_deploy:
  - cd docker_images/datahub
  - pwd
  - echo $DOCKER_USER
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=jeremyward/datahub
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
  - cd ..
  - cd ..