language: python
python:
- '3.6'
script:
- pytest
services:
- mongodb
deploy:
  provider: pypi
  user: jeremycward
  password:
    secure: VtG5RIRVJpFaJgZUPqAWO5FENUyGax2My58C7EYhVeEzbzoeGTscdq88RKYlKOGX7hqdhGB0vB7dbZS1AfCyxi0SJ8e45MWz/KNP8l/0ipJmfjTRLANUEwH4I6UwK6JaiQL/iSannLDTLxUioZm6cBQ57kmHMAWH0eg6Rk+XeRVqLVPfyRd9AljIZQAun2kvJ4Vrf3gKZCVcKzP2xBvUcxe3LwdEBj3C7g1yMwZ233GaevQSHKKP1nfD7qYSxPvfRsGbAOfSxccqULrnnCsX3RHjPvCCNvLdZnc9FvljA0GHKTW1CcN+tAwYzkMOqBaiwmLc1xI/p6TCbR1vflhRERiqQxnCLx82y25AsfT8ZzgUAyIGUcaXdCKcjeKNN3Apq8a414fVN72pgLX2f19TN84UO0asTfRyIAcnOqR+ZTlDFrhIj237QNpSbGSmzWNEHNQKDcnWpIJhvelATy7IxLI2j8Rc8MRgg3/T5JCmx0pXpvhUhoF5XN3CqjSsRRtU2SEVXCSMNxghNzSUqkkPaOJfRWL7aEP5QP43Jm7trKp/ndoXzueUMQvBcvTlh68jqoqzHJFZfXnN3S/slNNkvSGTIvFJeGZhUpmZrPu9bqKX+cctY2HpYOq5EtM9qbDpzBVpQu1nnmvrRVfy07NM4vO+zYAKBZuPxHP++zOJWI8=
  on:
    tags: true
    all_branches: true
