language: python
python:
- '3.6'
script:
- pytest
services:
- mongodb
deploy:
  provider: pypi
  user: jeremycward
  password:
    secure: qY9mGzSGXaQ4E8EC1OyTS9bJ8L2BRrNbHuIQnwko66tkXgxxh67t+cve2LkeEHOKZSmq/21LkRf8qsRPaSPAOSo6sNFdkI6KG/oWYDUUUrmEUOZHN4T2qw9w9PynhohG8qFVA90maPKLH3wWnbgJk+i2ff2ygLLJKB0RrOj2S1j5qtlGJHoBI7/gKrQs9ikpmr6JLwKzfjOuR4xmFRGsZepGyeLxyMS4sSvlwXY1G9I9p35XGquHmeG6G/di2w+bamvBxxVjiQzNddxUxmAQqNTu4xny6k2nT9BOqwKi9WpIlw4tAhqwRSdLU6OxRrOhyj50GhOyEFj3tO1YM1xpgRk+IVMMKnGZc9qam8dpKACAsQnTysbyP59F0glTuN5KyzgDDJDQjpR4l4IGoE/0TJl0bCMw6cfvaHaPm7uKJqrsyxRtI+ZzA65VRNuPs2F2ANVCJV5lAn00onA2F1xQTpbLXJnZmvsDzfDeT0qNulz8BhNfskZevCtJ8KcqpEoKiGaGyh2fy35Kh2VIViAyRVn6w+tyOSM9bJ4R86bqeaf0fhjmKUU8nY7jir1c9avwAifiqZNH0DuGu5L8ZJg7U1hJaPfvzaNMLjZjd0J1L6jZ/OJVxWT3ll8j2bunULMj1Q5vwsp8IIohvWzOFWbPgQTtoiNf8y95tX7ocObCGK8=
  skip_cleanup: true
  on:
    tags: true
