version: "3"
services:
  rabbit:
    container_name: isharp-rabbitmq
    image: rabbitmq:3.7-management
    ports:
      - "15672:15672"


  datahub:
    container_name: isharp-datahub
    image: datahub
    depends_on:
      - rabbit
    links:
      - rabbit:isharp-rabbitmq
     environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      RABBIT_MANAGEMENT_PORT: "15672"


