version: "3"
services:


  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"

  rabbit:
    container_name: isharp-rabbitmq
    image: rabbitmq:3.7-management
    ports:
      - "15672:15672"
      - "5672:5672"

  datahub:
    container_name: isharp-datahub
    image: datahub
    depends_on:
      - rabbit
      - mongo

    links:
      - "rabbit:isharp-rabbitmq"
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      RABBIT_MANAGEMENT_PORT: "15672"


