version: "3"
services:
  mq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15671:15671"
  datahub:
    # replace username/repo:tag with your name and image details
    image: jeremyward/datahub:latest

networks:
  webnet: