version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: jeremyward/mobysharp:demo
    ports:
      - "4000:80"
    networks:
      - webnet
networks:
  webnet: