version: "2"
services:


  mongo:
    container_name: isharp_mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"

  rabbit:
    container_name: isharp-rabbitmq
    image: rabbitmq:3.7-management
    ports:
      - "15672:15672"
      - "5672:5672"

  datahub:
    container_name: isharp-datahub
    image: datahub:demo
    ports:
      - "80:80"
      - "8888:8888"
      - "8082:8082"
    depends_on:
      - rabbit
      - mongo
    volumes:
      -  $HOME/isharpdemo/isharp-core/isharp/datahub/web/templates:/templates
      -  $HOME/isharpdemo/isharp-core/demo/jupyter:/jupyter
    links:
      - "rabbit:isharp-rabbitmq"
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      RABBIT_MANAGEMENT_PORT: "15672"
      isharp_hub_host: rabbit:5672
      isharp_web_templates: /templates
      mongo_host: mongo
      isharp_home: /isharp-core
      graph_host: graph
      datahub_host: localhost


  graph:
    container_name: isharp-graph
    image: neo4j
    volumes:
      - $HOME/neo4j/data:/data
    environment:
      NEO4J_AUTH: 'none'

    ports:
      - "7474:7474"
      - "7687:7687"

#  jupyter:
#    container_name: isharp-demo-jupyter


# docker run  --publish=7474:7474 --publish=7687:7687  --env=NEO4J_AUTH=none --volume=$HOME/neo4j/data:/data neo4j
