version: "3"
services:


  mongo:
    container_name: isharp_mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"

  init_mongo:
    container_name: isharp_mongo_demo_init
    image: arctic_demo_init
    depends_on:
      - mongo
    links:
      - "mongo:isharp_mongo"

    environment:
      mongo_password: "example"
      mongo_userid: "root"
      mongo_db_name: "isharp"
      mongo_init_skip: ""
      mongo_host: "mongo"

  rabbit:
    container_name: isharp-rabbitmq
    image: rabbitmq:3.7-management
    ports:
      - "15672:15672"
      - "5672:5672"

  datahub:
    container_name: isharp-datahub
    image: datahub
    depends_on:
      - rabbit
      - mongo

    links:
      - "rabbit:isharp-rabbitmq"
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      RABBIT_MANAGEMENT_PORT: "15672"


