version: "3"
services:
  mq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15671:15671"
  web:
    # replace username/repo:tag with your name and image details
    image: jeremyward/mobysharp:demo
    ports:
      - "4000:80"
    networks:
      - webnet
networks:
  webnet: